#ifndef CUBEPLUGIN_GLOBAL_H
#define CUBEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CUBEPLUGIN_LIBRARY)
#  define CUBEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CUBEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CUBEPLUGIN_GLOBAL_H
